# Это мое тестовое задание
name: Docker and Helm Build and Push


on:
  pull_request: # добавить еще и на пуш
    branches:
      - main
  push:
    branches:
      - main

env:
  CR_REGISTRY: ${{ vars.CR_REGISTRY }}
  CR_REPO: ${{ vars.CR_REPO }}

  

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    #environment: dev
    steps:


      - name: Checkout code
        uses: actions/checkout@v2

      #- name: Login in Yandex Cloud
      #  uses: yc-actions/yc-cr-login@v0.1-alpha
      #  with:
      #    yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}


      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Get version
        id: getver
        run: echo "GIT_VER=$(git describe --match "v*" --abbrev=4 --tags --always)-$GITHUB_RUN_NUMBER" >> $GITHUB_ENV

        
      #- name: Build and push
      #  uses: docker/build-push-action@v4
      #  with:
      #    push: true
      #    context: .
      #    tags: cr.yandex/${{ env.CR_REGISTRY }}/${{ env.CR_REPO }}:${{ env.GIT_VER }}
      
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: src/app/
          tags: ${{ env.CR_REGISTRY }}/${{ env.CR_REPO }}:${{ env.GIT_VER }}
      
    outputs:
          GIT_VER: ${{ env.GIT_VER }}
